In [1]:
import pandas as pd

df = pd.read_csv(
    "../../data/processed/credit_default_clean.csv"
)

df.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,TARGET_DEFAULT
0,20000,2,2,1,24,2,2,-1,-1,-2,...,0,0,0,0,689,0,0,0,0,1
1,120000,2,2,2,26,-1,2,0,0,0,...,3272,3455,3261,0,1000,1000,1000,0,2000,1
2,90000,2,2,2,34,0,0,0,0,0,...,14331,14948,15549,1518,1500,1000,1000,1000,5000,0
3,50000,2,2,1,37,0,0,0,0,0,...,28314,28959,29547,2000,2019,1200,1100,1069,1000,0
4,50000,1,2,1,57,-1,0,-1,0,0,...,20940,19146,19131,2000,36681,10000,9000,689,679,0

In [2]:
df.shape

(29965, 24)

In [4]:
from sdv.metadata import SingleTableMetadata

metadata = SingleTableMetadata.load_from_json(
    "../../reports/metadata/credit_default_metadata.json"
)

metadata.to_dict()

{'columns': {'LIMIT_BAL': {'sdtype': 'numerical'},
  'SEX': {'sdtype': 'categorical'},
  'EDUCATION': {'sdtype': 'categorical'},
  'MARRIAGE': {'sdtype': 'categorical'},
  'AGE': {'sdtype': 'numerical'},
  'PAY_0': {'sdtype': 'categorical'},
  'PAY_2': {'sdtype': 'categorical'},
  'PAY_3': {'sdtype': 'categorical'},
  'PAY_4': {'sdtype': 'categorical'},
  'PAY_5': {'sdtype': 'categorical'},
  'PAY_6': {'sdtype': 'categorical'},
  'BILL_AMT1': {'sdtype': 'numerical'},
  'BILL_AMT2': {'sdtype': 'numerical'},
  'BILL_AMT3': {'sdtype': 'numerical'},
  'BILL_AMT4': {'sdtype': 'numerical'},
  'BILL_AMT5': {'sdtype': 'numerical'},
  'BILL_AMT6': {'sdtype': 'numerical'},
  'PAY_AMT1': {'sdtype': 'numerical'},
  'PAY_AMT2': {'sdtype': 'numerical'},
  'PAY_AMT3': {'sdtype': 'numerical'},
  'PAY_AMT4': {'sdtype': 'numerical'},
  'PAY_AMT5': {'sdtype': 'numerical'},
  'PAY_AMT6': {'sdtype': 'numerical'},
  'TARGET_DEFAULT': {'sdtype': 'categorical'}},
 'METADATA_SPEC_VERSION': 'SINGLE_TABLE_V1'}

In [ ]:
# khoi tao model CTGAN
from sdv.single_table import CTGANSynthesizer

synthesizer = CTGANSynthesizer(
    metadata,
    epochs=100,
    verbose=True
)

epochs=100 de test sau nang len 300, 500

In [6]:
# Train model
synthesizer.fit(df)

/home/nao/synthetic-data-project/.venv/lib/python3.12/site-packages/torch/cuda/__init__.py:187: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0
Gen. (-00.79) | Discrim. (-00.14): 100%|██████████| 100/100 [08:22<00:00,  5.03s/it]

In [7]:
synthesizer.save(
    "../../models/ctgan_credit_default.pkl"
)

In [8]:
# sinh du lieu gia
synthetic_data = synthesizer.sample(
    num_rows=30000
)

synthetic_data.head()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,TARGET_DEFAULT
0,180320,1,3,1,44,-2,-2,-2,-2,-2,...,-1206,-883,15267,370,3190,7701,659,170,57,0
1,10000,1,3,2,40,0,0,0,0,0,...,1451,10629,13694,6481,0,112,3781,1203,124,0
2,134822,1,1,2,23,-1,-1,-1,-1,7,...,762,1024,1728,0,408,0,1621,1546,0,0
3,10000,2,3,2,47,0,0,0,0,0,...,17621,4354,12419,1616,6775,6588,677,169,949,0
4,74762,1,3,2,28,0,0,0,0,0,...,44070,56818,74824,4361,838,714,4484,292,5863,0

In [9]:
synthetic_data.shape

(30000, 24)

In [10]:
synthetic_data.to_csv(
    "../../data/synthetic/credit_default_synthetic.csv",
    index=False
)

In [11]:
synthetic_data.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,TARGET_DEFAULT
count,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,...,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000,30000.000000
mean,139880.597600,1.387733,2.093100,1.650167,37.032133,0.648433,0.579067,0.641333,0.573700,0.523133,...,34581.567700,37506.061600,43532.795867,2986.850100,2695.114900,3221.424233,4287.774200,3620.213767,5226.201967,0.263300
std,116367.325441,0.487241,1.044255,0.560887,9.016190,2.091613,2.081432,2.277059,2.275992,2.200930,...,54847.026546,65340.517854,70664.915723,6718.865722,7440.518287,7552.639935,9401.082608,7873.963605,17028.499472,0.440431
min,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-50986.000000,-19604.000000,-87939.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,46954.750000,1.000000,1.000000,1.000000,30.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,1116.750000,654.000000,1052.000000,119.750000,0.000000,0.000000,293.000000,184.000000,362.000000,0.000000
50%,115427.500000,1.000000,2.000000,2.000000,36.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,10103.000000,11563.000000,15421.500000,1517.500000,506.000000,1099.000000,1407.000000,1197.000000,1767.000000,0.000000
75%,194360.000000,2.000000,3.000000,2.000000,43.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,48257.750000,41063.250000,48389.250000,3180.000000,2598.000000,3254.000000,2675.250000,3609.000000,3274.000000,1.000000
max,684482.000000,2.000000,6.000000,3.000000,73.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,577091.000000,598541.000000,605222.000000,107923.000000,102949.000000,129349.000000,104363.000000,113192.000000,292813.000000,1.000000

In [12]:
df.describe()

,LIMIT_BAL,SEX,EDUCATION,MARRIAGE,AGE,PAY_0,PAY_2,PAY_3,PAY_4,PAY_5,...,BILL_AMT4,BILL_AMT5,BILL_AMT6,PAY_AMT1,PAY_AMT2,PAY_AMT3,PAY_AMT4,PAY_AMT5,PAY_AMT6,TARGET_DEFAULT
count,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000,...,29965.000000,29965.000000,29965.000000,29965.000000,2.996500e+04,29965.000000,29965.000000,29965.000000,29965.000000,29965.000000
mean,167442.005006,1.603738,1.853629,1.551877,35.487969,-0.016753,-0.131854,-0.164392,-0.218922,-0.264509,...,43313.329885,40358.334390,38917.012281,5670.099316,5.927983e+03,5231.688837,4831.617454,4804.897047,5221.498014,0.221258
std,129760.135222,0.489128,0.790411,0.521997,9.219459,1.123492,1.196322,1.195878,1.168175,1.132220,...,64353.514373,60817.130623,59574.147742,16571.849467,2.305346e+04,17616.361124,15674.464538,15286.372298,17786.976864,0.415101
min,10000.000000,1.000000,0.000000,0.000000,21.000000,-2.000000,-2.000000,-2.000000,-2.000000,-2.000000,...,-170000.000000,-81334.000000,-339603.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,50000.000000,1.000000,1.000000,1.000000,28.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,2360.000000,1787.000000,1262.000000,1000.000000,8.500000e+02,390.000000,300.000000,261.000000,131.000000,0.000000
50%,140000.000000,2.000000,2.000000,2.000000,34.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,19081.000000,18130.000000,17124.000000,2102.000000,2.010000e+03,1804.000000,1500.000000,1500.000000,1500.000000,0.000000
75%,240000.000000,2.000000,2.000000,2.000000,41.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,54601.000000,50247.000000,49252.000000,5008.000000,5.000000e+03,4512.000000,4016.000000,4042.000000,4000.000000,0.000000
max,1000000.000000,2.000000,6.000000,3.000000,79.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,891586.000000,927171.000000,961664.000000,873552.000000,1.684259e+06,896040.000000,621000.000000,426529.000000,528666.000000,1.000000